# Generated by Django 4.2.7 on 2023-12-01 10:13

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('patient_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('patient_fullname', models.CharField(max_length=255, verbose_name='Bemorning ism familiyasi')),
                ('patient_phone', models.IntegerField(verbose_name='Bemorning telefon raqami')),
                ('patient_adress', models.CharField(max_length=255, verbose_name='Bemorning manzili')),
                ('patient_age', models.IntegerField(verbose_name='Bemorning yoshi')),
            ],
        ),
    ]
