# Generated by Django 4.2.7 on 2023-12-08 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientcreate',
            name='check_in_date',
            field=models.DateField(),
        ),
    ]
