# Generated by Django 4.2.7 on 2023-12-13 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientcreate',
            name='patient_age',
            field=models.BigIntegerField(null=True, verbose_name='Bemorning yoshi'),
        ),
        migrations.AlterField(
            model_name='patientcreate',
            name='patient_phone',
            field=models.BigIntegerField(verbose_name='Bemorning telefon raqami'),
        ),
    ]
