# Generated by Django 4.2.7 on 2023-12-18 09:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_price', models.IntegerField(verbose_name="to'lov narxi")),
                ('discount', models.CharField(max_length=10, verbose_name='chegirma')),
                ('amount_paid', models.IntegerField(verbose_name="to'langan summa")),
                ('payment_term', models.CharField(max_length=255, verbose_name="to'lov muddati")),
                ('patient_fullname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_fullnamee', to='core.patientcreate', verbose_name='Bemorning ism familiyasi')),
                ('payment_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.patienthistory')),
            ],
        ),
    ]
