# Generated by Django 4.2.7 on 2023-12-04 17:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctorcreate',
            name='doctor_image',
        ),
        migrations.AddField(
            model_name='doctorcreate',
            name='doctor_university',
            field=models.TextField(default=1, verbose_name='doctor tamomlagan university'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='doctorcreate',
            name='muqova_image',
            field=models.ImageField(default=1, upload_to='user_info/', verbose_name='doktor muqova rasmi'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='doctorcreate',
            name='profile_image',
            field=models.ImageField(default=1, upload_to='user_info/', verbose_name='doktor profil rasmi'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='doctorcreate',
            name='work_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='patientcreate',
            name='check_in_date',
            field=models.DateTimeField(),
        ),
        migrations.DeleteModel(
            name='DoctorsList',
        ),
    ]
