# Generated by Django 4.2.7 on 2023-12-06 10:13

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctorcreate',
            name='doctor_image',
        ),
        migrations.AddField(
            model_name='doctorcreate',
            name='doctor_university',
            field=models.TextField(default=1, verbose_name='doctor tamomlagan university'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='doctorcreate',
            name='muqova_image',
            field=models.ImageField(default=1, upload_to='user_info/', verbose_name='doktor muqova rasmi'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='doctorcreate',
            name='profile_image',
            field=models.ImageField(default=1, upload_to='user_info/', verbose_name='doktor profil rasmi'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='doctorcreate',
            name='work_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='patientcreate',
            name='check_in_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='patientcreate',
            name='diseases',
            field=models.CharField(max_length=255, null=True, verbose_name='kasallik nommi'),
        ),
        migrations.AlterField(
            model_name='patientcreate',
            name='patient_acceptance',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.doctorcreate'),
        ),
        migrations.AlterField(
            model_name='patientcreate',
            name='patient_address',
            field=models.CharField(max_length=255, null=True, verbose_name='Bemorning manzili'),
        ),
        migrations.AlterField(
            model_name='patientcreate',
            name='patient_age',
            field=models.IntegerField(null=True, verbose_name='Bemorning yoshi'),
        ),
        migrations.AlterField(
            model_name='patientcreate',
            name='patient_blood',
            field=models.CharField(choices=[('α va β', 'birinchi (0)'), ('A va β', 'ikkinchi (A)'), ('α va B', 'uchinchi (B)'), ('A va B', 'toʻrtinchi (AB)')], max_length=255, null=True, verbose_name='Qon gruxi'),
        ),
        migrations.AlterField(
            model_name='patientcreate',
            name='patient_discription',
            field=models.TextField(null=True, verbose_name="Qo'shimcha ma'lumot"),
        ),
        migrations.AlterField(
            model_name='patientcreate',
            name='patient_fullname',
            field=models.CharField(max_length=255, null=True, verbose_name='Bemorning ism familiyasi'),
        ),
        migrations.AlterField(
            model_name='patientcreate',
            name='patient_gender',
            field=models.CharField(choices=[('Ayol', 'Ayol'), ('Erkak', 'Erkak')], max_length=255, null=True, verbose_name='Jinsi'),
        ),
        migrations.AlterField(
            model_name='patientcreate',
            name='patient_married',
            field=models.CharField(choices=[('Married', 'Married'), ('Unmarried', 'Unmarried')], max_length=255, null=True, verbose_name='Turmush holati'),
        ),
        migrations.AlterField(
            model_name='patientcreate',
            name='patient_room',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.rooms'),
        ),
        migrations.AlterField(
            model_name='patientcreate',
            name='patient_status',
            field=models.CharField(choices=[('Vip', 'Vip'), ('Oddiy', 'Oddiy'), ('Budjet', ' Budjet')], max_length=255, null=True, verbose_name='Qabul holati'),
        ),
        migrations.DeleteModel(
            name='DoctorsList',
        ),
    ]
