# Generated by Django 4.2.7 on 2023-12-21 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rooms',
            name='booked',
            field=models.CharField(choices=[("Bo'sh xona", "Bo'sh xona"), ('Band qilingan', 'Band qilingan')], default=1, max_length=255, verbose_name='xona holati'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rooms',
            name='room_status',
            field=models.CharField(choices=[('Vip', 'Vip'), ('Oddiy', 'Oddiy'), ('Budjet', ' Budjet')], default=1, max_length=255, verbose_name='xona turi'),
            preserve_default=False,
        ),
    ]
