# Generated by Django 4.2.7 on 2023-12-01 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='patient_blood',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B')], default=1, max_length=255),
            preserve_default=False,
        ),
    ]
