# Generated by Django 4.2.7 on 2023-12-11 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientcreate',
            name='patient_married',
            field=models.CharField(choices=[('Turmush qurgan', 'Turmush qurgan'), ('Turmush qurmagan', 'Turmush qurmagan')], max_length=255, null=True, verbose_name='Turmush holati'),
        ),
    ]
