# Generated by Django 4.2.7 on 2023-12-22 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rooms_booked_rooms_room_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='rooms',
            name='yotoq_soni',
            field=models.IntegerField(default=1, verbose_name='Yotoqlar soni'),
            preserve_default=False,
        ),
    ]
