# Generated by Django 4.2.7 on 2023-12-08 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_patientcreate_check_in_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientcreate',
            name='patient_birth',
            field=models.DateField(),
        ),
    ]
