# Generated by Django 4.2.7 on 2023-12-18 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patienthistory',
            name='payments',
            field=models.CharField(choices=[('Naqd pul', 'Naqd pul'), ('Plastik karta', 'Plastik karta'), ("Sug'urta", "Sug'urta")], max_length=20, verbose_name="to'lov turi"),
        ),
    ]
