# Generated by Django 4.2.7 on 2023-12-11 04:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_patientcreate_patient_married'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in_date', models.DateField(verbose_name="ruyxatdan o'tgan sanasi")),
                ('disease', models.CharField(max_length=255, verbose_name='kasallik turi')),
                ('retsept', models.TextField(verbose_name='kerakli dorilar')),
                ('payment', models.CharField(choices=[('cash', 'Naqd pul'), ('card', 'Plastik karta'), ('insurance', "Sug'urta")], max_length=20, verbose_name="to'lov tarixi")),
                ('patient_acceptance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_acceptances', to='core.doctorcreate')),
                ('patient_fullname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_fullnames', to='core.patientcreate', verbose_name='Bemorning ism familiyasi')),
            ],
        ),
    ]
