# Generated by Django 4.2.7 on 2023-12-29 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_payment_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='operation',
            name='operatsion_discount',
        ),
        migrations.RemoveField(
            model_name='operation',
            name='select_operatsion_serves',
        ),
        migrations.RemoveField(
            model_name='operation',
            name='total_grand',
        ),
    ]
