# Generated by Django 4.2.7 on 2023-12-01 10:27

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_patient_patient_blood'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorCreate',
            fields=[
                ('doctor_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('doctor_fullname', models.CharField(max_length=255, verbose_name='Doctorning ism familiyasi')),
                ('doctor_status', models.CharField(choices=[('Hamshira', 'Hamshira'), ('Kordiolog', 'Kordiolog')], max_length=255, verbose_name='Shifokorning lavozimi')),
            ],
        ),
        migrations.CreateModel(
            name='PatientCreate',
            fields=[
                ('patient_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('patient_fullname', models.CharField(max_length=255, verbose_name='Bemorning ism familiyasi')),
                ('patient_phone', models.IntegerField(verbose_name='Bemorning telefon raqami')),
                ('patient_adress', models.CharField(max_length=255, verbose_name='Bemorning manzili')),
                ('patient_age', models.IntegerField(verbose_name='Bemorning yoshi')),
                ('patient_blood', models.CharField(choices=[('A', 'A'), ('B', 'B')], max_length=255, verbose_name='Qon gruxi')),
                ('patient_status', models.CharField(choices=[('Vip', 'Vip'), ('Oddiy', 'Oddiy'), ('Budjet', ' Budjet')], max_length=255, verbose_name='Qabul holati')),
                ('patient_male', models.CharField(choices=[('Ayol', 'Ayol'), ('Erkak', 'Erkak')], max_length=255, verbose_name='Jinsi')),
                ('patient_acceptance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.doctorcreate')),
            ],
        ),
        migrations.DeleteModel(
            name='Patient',
        ),
    ]
