# Generated by Django 4.2.7 on 2023-12-06 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_doctorcreate_doctor_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientcreate',
            name='check_in_date',
            field=models.DateField(),
        ),
    ]
