# Generated by Django 4.2.7 on 2023-12-08 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_patientcreate_patient_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorcreate',
            name='doctor_birth',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='doctorcreate',
            name='work_time',
            field=models.TimeField(),
        ),
    ]
