# Generated by Django 4.2.7 on 2023-12-11 10:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_patienthistory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patienthistory',
            name='payment',
        ),
        migrations.AddField(
            model_name='patienthistory',
            name='patient_status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='bemor_turi', to='core.patientcreate'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patienthistory',
            name='payment_price',
            field=models.IntegerField(default=1, verbose_name="to'lov narxi"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patienthistory',
            name='total_status',
            field=models.CharField(choices=[("to'lov qilinmagan", "to'lov qilinmagan"), ("to'lov qilingan", "to'lov qilingan")], default=1, max_length=255, verbose_name="to'lov holati"),
            preserve_default=False,
        ),
    ]
