# Generated by Django 4.2.7 on 2023-12-18 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_patienthistory_payments'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='payment_card',
            new_name='payments',
        ),
    ]
