# Generated by Django 4.2.7 on 2023-12-01 22:09

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_rename_patient_adress_patientcreate_patient_address_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rooms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.IntegerField(blank=True, null=True, verbose_name='xona raqami')),
            ],
        ),
        migrations.CreateModel(
            name='PatientList',
            fields=[
                ('patient_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('check_in', models.DateTimeField(verbose_name='Bemorning kirish sanasi')),
                ('disease_type', models.CharField(max_length=255, verbose_name='kasallik turi')),
                ('patient_status', models.CharField(choices=[('Vip', 'Vip'), ('Oddiy', 'Oddiy'), ('Budjet', ' Budjet')], max_length=255, verbose_name='bemor turi')),
                ('doctor_assgined', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.doctorcreate', verbose_name='tayinlangan doktor')),
                ('patient_fullname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.patientcreate', verbose_name='Bemorning ism familiyasi')),
                ('room_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.rooms', verbose_name='Bemorning xona raqami')),
            ],
        ),
    ]
