# Generated by Django 4.2.7 on 2023-12-19 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_rename_payment_card_payment_payments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='payments',
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_choice',
            field=models.CharField(choices=[('Naqd pul', 'Naqd pul'), ('Plastik karta', 'Plastik karta'), ("Sug'urta", "Sug'urta")], default=1, max_length=20, verbose_name="to'lov turi"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='payment',
            name='discount',
            field=models.IntegerField(verbose_name='chegirma'),
        ),
    ]
