# Generated by Django 4.2.7 on 2023-12-26 01:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='doctor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.doctorcreate'),
            preserve_default=False,
        ),
    ]
