# Generated by Django 4.2.7 on 2023-12-11 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_patienthistory_patient_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='patienthistory',
            name='payments',
            field=models.CharField(choices=[('cash', 'Naqd pul'), ('card', 'Plastik karta'), ('insurance', "Sug'urta")], default=1, max_length=20, verbose_name="to'lov turi"),
            preserve_default=False,
        ),
    ]
