# Generated by Django 4.2.7 on 2023-12-02 20:59

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_rooms_room_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorsList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flaction_star', models.CharField(max_length=255, verbose_name='yulduzcha')),
                ('doctor_status', models.CharField(choices=[('Tibbiyot mutaxassisi', 'Tibbiyot mutaxassisi'), ('Ginekolog', 'Ginekolog'), ('Jismoniy terapiya', 'Jismoniy terapiya'), ('Audiologiya', 'Audiologiya'), ('Kordiolog', 'Kordiolog'), ('Hamshira', 'Hamshira')], max_length=255, verbose_name='Shifokorning lavozimi')),
                ('work_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('doctor_university', models.TextField(verbose_name='doctor tamomlagan university')),
                ('doctor_address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='address', to='core.doctorcreate')),
                ('doctor_fullname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ism', to='core.doctorcreate')),
            ],
        ),
    ]
