# Generated by Django 4.2.7 on 2023-12-11 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_patienthistory_payments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patienthistory',
            name='payment_price',
            field=models.BigIntegerField(verbose_name="to'lov narxi"),
        ),
    ]
