# Generated by Django 4.2.7 on 2023-12-04 07:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_doctorslist'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expense_head', models.CharField(max_length=255, verbose_name='harajat nomi')),
                ('select_category', models.CharField(choices=[("Kommunal xizmatlar uchun to'lov", "Kommunal xizmatlar uchun to'lov"), ("Ta'mirlash uskunalari uchun to'lov", "Ta'mirlash uskunalari uchun to'lov"), ("Kerakli retseptlar uchun to'lov", "Kerakli retseptlar uchun to'lov")], max_length=255)),
                ('amount', models.IntegerField(verbose_name='miqdori')),
                ('expense_date', models.DateTimeField()),
                ('discreption', models.TextField(verbose_name='tavsilot kiriting')),
                ('card_number', models.IntegerField(verbose_name='**** **** **** 5648')),
                ('select_bank', models.CharField(choices=[('NBU Bank', 'NBU Bank'), ('Hamkor Bank', 'Hamkor Bank'), ('Humo Xalq Banki', 'Humo Xalq Banki')], max_length=255, verbose_name='kerakli bankni tanlang')),
            ],
        ),
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operatsion_date', models.DateField()),
                ('operatsion_time', models.TimeField()),
                ('select_operatsion_type', models.CharField(choices=[("Ko'krak jarrohligi", "Ko'krak jarrohligi"), ("Ko'z jarrohligi", "Ko'z jarrohligi")], max_length=255, verbose_name='operatsiya turini tanlang')),
                ('select_operatsion_serves', models.CharField(choices=[("Ko'krak jarrohligi", "Ko'krak jarrohligi"), ("Ko'z jarrohligi", "Ko'z jarrohligi")], max_length=255, verbose_name='operatsiya xizmat turini tanlang')),
                ('operatsion_price', models.IntegerField(verbose_name='operatsiya narxi')),
                ('operatsion_discount', models.IntegerField(verbose_name='chegirma summasi')),
                ('total_grand', models.IntegerField(verbose_name='umumiy grand narxi')),
                ('paid_amount', models.IntegerField(verbose_name="to'langan miqdor")),
                ('comment', models.TextField(verbose_name='Izoh qoldiring')),
                ('patient_fullname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.patientcreate', verbose_name='Bemorning ism familiyasi')),
            ],
        ),
    ]
