# Generated by Django 4.2.7 on 2023-12-06 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_patientcreate_check_in_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rooms',
            name='room_number',
            field=models.IntegerField(blank=True, null=True, verbose_name='xona raqami'),
        ),
    ]
