# Generated by Django 4.2.7 on 2023-12-13 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_patienthistory_payment_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addexpense',
            name='amount',
            field=models.CharField(max_length=25, verbose_name='miqdori'),
        ),
    ]
